### ISSUE TITLE
Is it live?

### ISSUE THREAD

**Issue by serhii-londar** [Shikachuu/UnderlordsLeaderboardsAPI#1]
@Shikachuu Thank for your project. Is this API live currently?

**Comment by Shikachuu** [comment]
Of course :D I just started it today, so it must be, I guess 👍

**Comment by serhii-londar** [comment]
I'm sorry I mean is it deployed somewhere and I can get data?

**Comment by Shikachuu** [comment]
Not yet, the project is created just today at 13pm (utc) so the first release is not even finished.
